import Foundation

/// Application UI language is independent of subtitle languages and the system locale.
public enum InterfaceLanguage: String, CaseIterable { case zh, en
    public static let preferenceKey="editor.interfaceLanguage"
    public static var preferred: InterfaceLanguage { InterfaceLanguage(rawValue:UserDefaults.standard.string(forKey:preferenceKey) ?? "") ?? .zh }
    public static let current=preferred
}
public func L(_ key: String, _ arguments: [String] = []) -> String {
    return UILocalization.text(key,arguments:arguments,language:InterfaceLanguage.current)
}
public enum UILocalization {
    public static func text(_ key: String, arguments: [String] = [], language: InterfaceLanguage) -> String {
        let template=language == .en ? (english[key] ?? key) : key
        // Match only the template, never tokens that happen to occur in user data.
        let pattern=try! NSRegularExpression(pattern:"\\{([0-9]+)\\}")
        let ns=template as NSString
        var output=template
        for match in pattern.matches(in:template,range:NSRange(location:0,length:ns.length)).reversed() {
            if let index=Int(ns.substring(with:match.range(at:1))),arguments.indices.contains(index),let range=Range(match.range,in:output) {
                output.replaceSubrange(range,with:arguments[index])
            }
        }
        return output
    }
    public static let english: [String:String] = [
        "已取鼠标起点颜色 · 框选后按 Delete 应用": "Start-point color sampled · Select a region and press Delete",
        "起点取色失败，请重新框选：{0}": "Could not sample the start point. Select again: {0}",
        "从背景处按下鼠标取色并框选；Delete 去字，Esc 取消": "Start dragging on the background to sample its color; Delete to remove text, Esc to cancel",
        "取色失败，请重新框选": "Color sampling failed. Select the region again",
        "正在读取起点颜色，请稍后按 Delete": "Sampling the start point. Press Delete in a moment",
        "默认使用框选起点的视频颜色，可手动调整。勾选自动匹配后改用底边逐帧取色。时间相对于当前片段，Y 从底部计算。": "Uses the video color at the drag start point by default; you can adjust it manually. Enable automatic matching to sample the bottom edge each frame instead. Times are relative to this clip; Y starts at the bottom.",
        "{0} 失败（{1}）\n{2}\n日志：{3}": "{0} failed ({1})\n{2}\nLog: {3}",
        " · Dolby Vision 基础层": " · Dolby Vision base layer",
        " · 双击视频片段编辑": " · Double-click a clip to edit",
        "FR / ZH  ·  本地视频工作台": "FR / ZH · Local video studio",
        "FR · 法语": "FR · French",
        "SDR / 未标记 HDR": "SDR / HDR not tagged",
        "Skill 目录": "Skill folder",
        "ZH · 中文": "ZH · Chinese",
        "\nDolby Vision 动态元数据不会保留，只可处理兼容基础层。": "\nDolby Vision dynamic metadata is not retained; only the compatible base layer is supported.",
        "\nHDR 为重新编码，非逐位无损；显示效果还取决于屏幕。": "\nHDR is re-encoded, not bit-for-bit lossless. Appearance also depends on your display.",
        "\n时间单位：秒。叠化与前一片段重叠，字幕跟随剪辑。": "\nTimes are in seconds. Dissolves overlap the preceding clip; subtitles follow edits.",
        "\n混合色彩格式：本版仅提供 SDR 输出，避免误标 HDR。": "\nMixed color formats: only SDR export is available to avoid incorrect HDR tagging.",
        "{0} · {1} 秒": "{0} · {1} sec",
        "{0} 条字幕": "{0} subtitles",
        "{0} 条文字": "{0} text clips",
        "上下拖动调整预览与时间轴高度；双击恢复默认": "Drag vertically to resize preview and timeline; double-click to reset",
        "不保存并新建": "Discard and create",
        "不能覆盖源视频": "Cannot overwrite a source video",
        "与前片段叠化": "Dissolve from previous",
        "中": "Center",
        "中文": "Chinese",
        "亮度（-1～1）": "Brightness (−1 to 1)",
        "人工修改的字幕将被替换，完成后可通过撤销恢复。": "Manually edited subtitles will be replaced. You can undo this after generation.",
        "任务正在进行": "Task in progress",
        "位置 · %，Y 从底部计算": "Position · %, Y from bottom",
        "位置和样式自动应用于同轨全部文字": "Style applies to the whole track",
        "你好 一段新的故事": "你好 一段新的故事",
        "保存": "Save",
        "保存字幕工程": "Save subtitle project",
        "保存工程…": "Save Project…",
        "保存并新建": "Save and create",
        "保存并检查": "Save and Check",
        "保存当前工程后再新建？": "Save the current project before creating a new one?",
        "修改区域去字": "Edit text removal region",
        "全选": "Select All",
        "写入视频失败": "Failed to write video",
        "准备就绪": "Ready",
        "分割视频": "Split video",
        "切换字幕显示": "Toggle subtitles",
        "删除区域": "Delete region",
        "删除去字区域": "Delete text removal region",
        "删除字幕": "Delete subtitle",
        "删除所选文字轨道及全部文字片段（⌘Z 可撤销）": "Delete selected text track and all its clips (⌘Z to undo)",
        "删除文字轨道": "Delete text track",
        "删除片段右侧": "Trim right of playhead",
        "删除片段左侧": "Trim left of playhead",
        "删除视频片段": "Delete video clip",
        "删除轨道": "Delete Track",
        "删除选中视频在播放头右侧的部分": "Remove the selected clip after the playhead",
        "删除选中视频在播放头左侧的部分": "Remove the selected clip before the playhead",
        "剪切": "Cut",
        "区域 {0} · {1} · {2}–{3} 秒": "Region {0} · {1} · {2}–{3} sec",
        "区域去字": "Remove Text",
        "去字": "Remove",
        "取消": "Cancel",
        "取消任务并退出": "Cancel Task and Quit",
        "叠化": "Dissolve",
        "右": "Right",
        "四角调字号 · 左右手柄调宽度": "Corners: size · Sides: width",
        "在播放头分割视频": "Split Video at Playhead",
        "在播放头分割视频（⌘B）": "Split video at playhead (⌘B)",
        "垂直 Y": "Vertical Y",
        "增强可读性（对比描边与阴影）": "Improve text contrast",
        "复制": "Copy",
        "复用本机 Codex 登录。转写在本机进行，字幕文本发送到 Codex 翻译；首次转写可能下载模型。": "Uses your local Codex login. Transcription runs locally; subtitle text is sent to Codex for translation. The first transcription may download a model.",
        "字体": "Font",
        "字体与样式": "Font & Style",
        "字号": "Size",
        "字幕": "Subtitles",
        "字幕内容不能为空；移除字幕请使用删除按钮": "Subtitle text cannot be empty. Use Delete to remove a subtitle.",
        "字幕和样式已保留，请重新定位：\n{0}": "Subtitles and styles are preserved. Locate the video:\n{0}",
        "字幕属性": "Inspector",
        "字幕属性面板": "Inspector panel",
        "字幕工坊": "Subtitle Studio",
        "字幕工坊 · Video Éditeur": "Subtitle Studio · Video Éditeur",
        "宽度 %": "Width %",
        "宽度请输入 10 到 100，留空恢复自动宽度": "Enter a width from 10 to 100; leave blank for automatic width",
        "对比度（0～2）": "Contrast (0 to 2)",
        "对齐": "Alignment",
        "导入视频": "Import Video",
        "导入视频…": "Import Video…",
        "导出失败": "Export failed",
        "导出完成：{0}": "Export complete: {0}",
        "导出已取消": "Export cancelled",
        "导出已取消或未完成": "Export cancelled or incomplete",
        "导出视频": "Export Video",
        "尚未导入视频": "No video imported",
        "工具路径检查通过": "Tool paths verified",
        "工程已保存：{0}": "Project saved: {0}",
        "左": "Left",
        "左侧 X %": "Left X %",
        "左右拖动调整{0}宽度；双击恢复默认": "Drag horizontally to resize {0}; double-click to reset",
        "已取消区域框选": "Region selection cancelled",
        "已框选区域 · 按 Delete 设置背景覆盖，Esc 取消": "Region selected · Press Delete to fill with background; Esc to cancel",
        "已用背景色覆盖选区 · ⌘Z 撤销；视频剪辑菜单可管理去字区域": "Region filled · ⌘Z to undo; manage regions in the Video menu",
        "应用": "Apply",
        "底部 Y %": "Bottom Y %",
        "开始": "Start",
        "开始 · 秒": "Start · sec",
        "所选区间没有可用视频画面": "No video frames in the selected range",
        "所选视频时长与工程不一致，请选择原视频": "The video duration differs from the project. Select the original video.",
        "手动背景色": "Fill color",
        "打开工程…": "Open Project…",
        "找不到原视频": "Original video not found",
        "找不到视频素材": "Video asset not found",
        "找不到视频：{0}": "Video not found: {0}",
        "拖入法语视频，开始制作中文与法语字幕": "Drop a French video to create French and Chinese subtitles",
        "拖动框选原视频文字，底边留少量纯背景；按 Delete 去字，Esc 取消": "Drag to select embedded text, leaving a clean bottom edge. Delete to remove; Esc to cancel.",
        "拖动片段调整时间 · 拖动边缘调整时长": "Drag clips to move · Drag edges to trim",
        "拖动裁剪视频": "Trim video",
        "描边宽度": "Outline",
        "描边颜色": "Outline color",
        "撤销": "Undo",
        "播放": "Play",
        "播放 / 暂停（空格）": "Play / Pause (Space)",
        "文件": "File",
        "文字 {0}": "Text {0}",
        "文字在字幕框内左对齐、居中或右对齐": "Align text left, center or right within its box",
        "文本内容": "Text",
        "新工程 · 请导入视频": "New project · Import a video to start",
        "新建": "New",
        "新建将清空当前界面中的视频、字幕和时间轴。原视频和已保存的工程文件不会删除。": "This clears the current video, subtitles and timeline from the editor. Source videos and saved project files will not be deleted.",
        "新建工程": "New Project",
        "新建文字轨道": "New Text Track",
        "无法创建剪辑音频": "Cannot create edited audio",
        "无法创建合成画面": "Cannot create a composite frame",
        "无法开始导出": "Cannot start export",
        "无法绘制字幕": "Cannot draw subtitles",
        "无法读取视频，请选择支持的 MP4 或 MOV 文件": "Cannot read video. Choose a supported MP4 or MOV file.",
        "无法读取视频：{0}": "Cannot read video: {0}",
        "时间 · 秒": "Time · sec",
        "时间轴": "Timeline",
        "时间轴没有音轨，无法生成语音字幕": "The timeline has no audio track for transcription",
        "显示背景": "Show background",
        "暂停": "Pause",
        "最小化": "Minimize",
        "本机工具设置": "Settings",
        "框选区域去字": "Select Text Removal Region",
        "框选原视频文字，按 Delete 用背景色覆盖": "Select embedded text, then press Delete to fill with background color",
        "正在取消…": "Cancelling…",
        "正在导出 {0}…": "Exporting {0}…",
        "正在导出 · {0}%": "Exporting · {0}%",
        "正在混合剪辑音频…": "Mixing edited audio…",
        "此 Mac 不支持所选视频编码格式，请选择 SDR 或更换设备": "This Mac does not support the selected codec. Choose SDR or another device.",
        "此视频片段暂无去字区域，点击「区域去字」开始框选": "No removal regions in this clip. Click Remove Text to select a region.",
        "水平 X": "Horizontal X",
        "法中字幕已生成 · {0} 组": "French / Chinese subtitles ready · {0} pairs",
        "法语": "French",
        "淡入": "Fade in",
        "淡出": "Fade out",
        "添加": "Add",
        "添加区域去字": "Add text removal region",
        "添加字幕": "Add subtitle",
        "添加文字": "Add Text",
        "添加视频": "Add video",
        "添加视频到当前时间轴": "Add videos to the timeline",
        "添加视频到时间轴…": "Add Videos to Timeline…",
        "源视频终点": "Source end",
        "源视频起点": "Source start",
        "点击显示或收起面板；选中表示已展开": "Toggle panel visibility; selected means visible",
        "生成已停止 · 已保留完成的字幕，可继续重试": "Generation stopped · Completed subtitles are preserved; you can retry",
        "生成法中字幕": "Generate FR/ZH",
        "生成部分字幕": "Generate partial subtitles",
        "用背景色覆盖选区文字": "Fill selected text with background color",
        "目标文字轨道": "Target text track",
        "稍后": "Later",
        "窗口": "Window",
        "管理去字区域": "Manage Text Removal Regions",
        "管理去字区域…": "Manage Text Removal Regions…",
        "粘贴": "Paste",
        "素材": "Media",
        "素材 / 字幕": "Media / Subtitles",
        "素材不可用": "Media unavailable",
        "素材与字幕分类": "Media and subtitle categories",
        "素材时长不匹配，请选择原视频": "Duration mismatch. Select the original video.",
        "素材色彩格式不一致，无法保真导出所选 HDR 格式": "Mixed source color formats cannot preserve the selected HDR format",
        "素材面板": "Media panel",
        "结束": "End",
        "结束 · 秒": "End · sec",
        "继续字幕生成": "Resume Subtitles",
        "继续导出": "Continue Export",
        "继续工作": "Keep Working",
        "编辑": "Edit",
        "编辑去字区域": "Edit Text Removal Region",
        "编辑字幕": "Edit subtitle",
        "编辑字幕属性": "Edit subtitle properties",
        "背景颜色": "Background",
        "自动": "Auto",
        "自动保存失败：{0}": "Autosave failed: {0}",
        "自动匹配底边背景色（取消勾选使用下方颜色）": "Match bottom-edge color (uncheck to use the color below)",
        "自动模式逐帧取选区内底边的平均颜色，适合纯色底条。底边请避开文字。复杂纹理不会自动还原。时间相对于当前视频片段，Y 从底部计算。": "Automatic mode samples the average bottom-edge color each frame. It works best on solid bars: keep text out of that edge. Complex textures are not restored. Times are relative to this clip; Y is measured from the bottom.",
        "自动背景色": "Automatic color",
        "自定义样式": "Custom style",
        "裁剪与特效…": "Trim & Effects…",
        "视频": "Video",
        "视频剪辑": "Video",
        "视频剪辑 / 特效": "Video / Effects",
        "视频剪辑与特效": "Video Editing & Effects",
        "视频已加载 · {0} × {1}": "Video loaded · {0} × {1}",
        "视频时长无效": "Invalid video duration",
        "视频片段前移": "Move Clip Earlier",
        "视频片段后移": "Move Clip Later",
        "视频编码设置不受支持": "Video encoding settings are unsupported",
        "视频缺少格式信息": "Video format information is missing",
        "视频裁剪与特效": "Video trim and effects",
        "让每一句话 都被看见": "让每一句话 都被看见",
        "让每一句话，都被看见": "Make every word visible",
        "设置…": "Settings…",
        "请先取消或等待当前任务完成，再新建工程": "Finish or cancel the current task before creating a new project",
        "请先添加视频": "Add a video first",
        "请先选中法语或中文": "Select French or Chinese first",
        "请输入有效坐标和片段内时间": "Enter valid coordinates and times within this clip",
        "请输入有效数值": "Enter valid numeric values",
        "读取视频片段失败": "Failed to read video clip",
        "调整{0}宽度": "Resize {0}",
        "调整同语言字幕宽度": "Change subtitle track width",
        "调整同语言字幕样式": "Change subtitle track style",
        "调整视频顺序": "Reorder video clips",
        "调整预览与时间轴高度": "Resize preview and timeline",
        "轨道样式": "Track style",
        "退出会取消当前任务，已完成字幕仍会保存。": "Quitting cancels the current task. Completed subtitles will be saved.",
        "退出字幕工坊": "Quit Subtitle Studio",
        "选择字幕开始编辑": "Select a subtitle to edit",
        "选择输出格式": "Choose Output Format",
        "重做": "Redo",
        "重新定位": "Locate Video",
        "重新生成": "Regenerate",
        "重新生成将替换现有字幕": "Regenerating will replace existing subtitles",
        "面板显示开关": "Panel visibility",
        "音频准备已取消": "Audio preparation cancelled",
        "音频准备已取消或失败": "Audio preparation cancelled or failed",
        "音频编码设置不受支持": "Audio encoding settings are unsupported",
        "预览": "Preview",
        "颜色": "Color",
        "饱和度（0～2）": "Saturation (0 to 2)",
        "高度 %": "Height %",
        "界面语言": "Interface language",
        "语言更改将在下次启动时生效。": "The language change takes effect next time you start the app.",
        "语言设置已保存": "Language preference saved",
        "好": "OK",
        "SRT 包含重叠、空文本或无效时段": "SRT contains overlapping, empty or invalid intervals",
        "SRT 时间格式错误": "Invalid SRT time format",
        "SRT 条目格式错误": "Invalid SRT entry",
        "Skill 文件缺失：{0}": "Missing skill file: {0}",
        "不支持的工程版本：{0}": "Unsupported project version: {0}",
        "中文翻译 · {0} / {1}": "Chinese translation · {0} / {1}",
        "中文翻译 · 重试第 {0} 批": "Chinese translation · Retrying batch {0}",
        "任务已取消": "Task cancelled",
        "剪辑时间轴长度不一致": "Edited timeline duration is inconsistent",
        "去字区域 ID 重复": "Duplicate text removal region ID",
        "去字区域或生效时间无效": "Invalid removal region or time range",
        "去字背景颜色无效": "Invalid removal background color",
        "字幕 {0} 的翻译为空或未包含中文，请重试该批次": "Translation at {0} is empty or contains no Chinese. Retry this batch.",
        "字幕宽度须在 10% 到 100% 之间": "Subtitle width must be between 10% and 100%",
        "字幕时间重叠、越界或内容为空": "Subtitle times overlap, exceed the video, or text is empty",
        "字幕样式数值无效": "Invalid subtitle style values",
        "工具运行超时，可重试。日志：{0}": "Tool timed out. Retry; log: {0}",
        "工程时间或字幕 ID 无效": "Invalid project time or subtitle ID",
        "当前位置已有字幕，请移动播放头或调整字幕时间": "There is already a subtitle here. Move the playhead or adjust its time.",
        "当前位置没有可用时间区间": "No available time interval at this position",
        "找不到 {0}：{1}\n请在设置中修正路径": "Cannot find {0}: {1}\nCorrect the path in Settings",
        "提取音频 · 16 kHz": "Extracting audio · 16 kHz",
        "播放位置已在视频末尾": "The playhead is already at the end",
        "文字轨道 ID 无效": "Invalid text track ID",
        "文字轨道不存在": "Text track does not exist",
        "无效时间：{0}": "Invalid time: {0}",
        "未识别到法语语音": "No French speech detected",
        "校验双语字幕": "Validating bilingual subtitles",
        "法语转写 · Whisper / 首次使用可能下载模型": "French transcription · Whisper / First use may download a model",
        "法语转写 · 切换 CPU 引擎": "French transcription · Switching to CPU",
        "翻译失败，请重试": "Translation failed. Please retry.",
        "翻译返回缺失或重复的字幕 ID": "Translation contains missing or duplicate subtitle IDs",
        "视频片段 ID 重复": "Duplicate video clip ID",
        "视频裁剪或特效参数无效：叠化不能超过相邻片段一半，淡入淡出不能超过片段时长": "Invalid trim or effect values: dissolves cannot exceed half of either adjacent clip, and fades cannot exceed clip duration",
        "请先选择视频片段": "Select a video clip first",
        "请在片段内部、叠化区域以外分割": "Split inside the clip, outside any dissolve",
        "请将播放头放在要裁剪的视频片段内部": "Move the playhead inside the clip to trim it"
    ]
}
